% calculate the blended value of a decision
function BlendedValue2 = CalcBlendedValPlayer2 (instance1, instance2, instance3, instance4)
    BlendedValue2 = (instance1.P2O * instance1.Re) + ...
        (instance2.P2O * instance2.Re) + (instance3.P2O * instance3.Re)...
        +(instance4.P2O * instance4.Re);